### ISSUE TITLE
Legality Anlaysis

### ISSUE THREAD

**Issue by kamronbatman** [porybox/porybox#580]
Hi everyone.

I would like to start a discussion about Legality Analysis. Of course once PokeBank supports Gen 7, this will become ever more important.

Here are some (probably not all) keypoints:

1) Put together a database of all event pokemon from gen 3 to 7. I think between my personal collection, theSLAYER, RoC, and users from /r/pokemonexchange, we can get almost everything. This database does NOT have to be public or included in the repo.

2) Identify the moving parts (What checks do we need). E.g. PID/IV algorithms, TID/SIDs of event pokemon, etc. This applies for both event pokemon and in-game encounters. I'll be happy to help with the knowledge I gathered building the legality checker, and from the many others that have contributed to this research.

3) Determine if this should be done on the back end completely, or on the front end as well. The reason this is important is because of PID/IV algorithms which require seed searching.

**Comment by kamronbatman** [comment]
Ref #92. We definitely should scrape all WCs and pokemon.

**Comment by not-an-aardvark** [comment]
We have a (very much WIP) legality checker here: https://github.com/porygonco/pokemon-legality-checker

This has been in progress for awhile, although development on it has stalled a bit recently while we work on getting support for gen 7. Help on it would certainly be appreciated.

In response to (3), I think it would be simplest if the check was completely on the backend, so that we wouldn't have to send a large amount of legality data to the client. Also, keep in mind that the client sometimes doesn't have all the information on a Pokémon (e.g. it doesn't have the PID unless the user is the owner), so it would only be able to do a limited amount of analysis anyway.

**Comment by kamronbatman** [comment]
That is true, so that answers #3. I just hope we don't have scaling issues.
I started to look at that repo, and was wondering why the legality analysis is not built into porybox directly?

**Comment by not-an-aardvark** [comment]
We mostly separated it to make it easier to maintain, since it also works on its own as a separate module. Eventually, we can update porybox to add it as a dependency so that we can use it to display legality on the site.

**Comment by YaManicKill** [comment]
Closing as this is covered by lots of other things.
