### ISSUE TITLE
Turn off individual elements from viewing?

### ISSUE THREAD

**Issue by YaManicKill** [porybox/porybox#629]
When we get legality, this might be a bit better, because 1 big problem with this is people can hide bits of the pokemon that are dodgy looking (although, maybe that's not an issue because they could just edit them if they are).

This was suggested [on reddit](https://www.reddit.com/r/porybox/comments/5nnm4d/could_we_possibly_turn_on_and_off_the_ivs_so_we/). I expanded it to allow most things to be turned off.

**Comment by not-an-aardvark** [comment]
Meh, I'm not a big fan of this idea. I think people would use it to hide sketchy things (e.g. a region history that doesn't match where they claim something came from), and I don't really see the benefit of it.

The comment on reddit suggested hiding IVs for static PID events, which is probably a good idea (https://github.com/porygonco/porybox/issues/36), but I think that should be automatic rather than giving users the ability to hide arbitrary parts of a pokemon.

**Comment by Raia** [comment]
I agree with naa. There isn't much benefit other than letting people be sketchy, and something like this would defeat the purpose of having Porybox as a viewer that shows everything.

**Comment by YaManicKill** [comment]
Aight. Closing.
